### PR TITLE
Wait for Elasticsearch to start before indexing

### LINKED ISSUE #179: Indexing on startup fails when Elasticsearch starts slowly
https://github.com/WISVCH/dienst2/blob/47a59c426eef43ed586d70e261e173a0f475bf53/docker-entrypoint.sh#L6
When Elasticsearch starts slowly (e.g. high system load), indexing will fail, and Dienst2 will start with an empty index.

### PR DESCRIPTION
**Pull request by praseodym**
Fixes #179

### CODE REVIEW

File: docker-entrypoint.sh [hunk 1]
```diff
@@ -3,6 +3,10 @@ set -e
 
 if [ "$1" = 'gunicorn' ]; then
     ./manage.py migrate --noinput
+    until curl -sf http://localhost:9200 > /dev/null; do
```
Comment (svenpopping) [inline docker-entrypoint.sh]: What if Elasticsearch fails to startup?

Comment (praseodym) [reply docker-entrypoint.sh]: Good point. Let’s define a readiness probe for the Elasticsearch container in Kubernetes, so that the Dienst2 pod will fail to start when Elasticsearch fails to start.

Comment (svenpopping) [reply docker-entrypoint.sh]: 👍

Comment (praseodym) [reply docker-entrypoint.sh]: Done
